{"lesson":{"id":2440,"name":"Exceptions","type":0,"mode":1,"videoID":null,"tags":"exceptions","quizzes":[{"id":5037,"number":1,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":1,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":98081,"text":"An event that occurs due to incorrect code or input","isCorrect":true,"properties":{}},{"id":98082,"text":"A variable","isCorrect":false,"properties":{}},{"id":98083,"text":"A function","isCorrect":false,"properties":{}}],"question":"What is an exception?","textContent":"[h1]Exceptions[/h1]\r\n\r\nYou have already seen [b]exceptions [/b]in previous code. They occur when something goes wrong, due to incorrect code or input. When an exception occurs, the program immediately stops.\r\nThe following code produces the ZeroDivisionError exception by trying to divide 7 by 0.  [code format=\"py\" codeId=\"343\"]num1 = 7\r\nnum2 = 0\r\nprint(num1/num2)[/code]\r\n[b]Result:[/b] [code format=\"raw\" ]>>>\r\nZeroDivisionError: division by zero\r\n>>>[/code]"},{"id":5038,"number":2,"videoStart":0.0,"videoEnd":0.0,"linkedVideoID":null,"type":1,"linkedQuizID":null,"tip":null,"hint":null,"time":0,"answers":[{"id":87631,"text":"ValueError","isCorrect":false,"properties":{}},{"id":87632,"text":"TypeError","isCorrect":true,"properties":{}},{"id":87633,"text":"ZeroDivisionError","isCorrect":false,"properties":{}}],"question":"Which exception is raised by this code?\r\nprint(\"7\" + 4)","textContent":"[h1]Exceptions[/h1]\r\n\r\nDifferent exceptions are raised for different reasons. \r\nCommon exceptions:\r\n[b]ImportError[/b]: an import fails;\r\n[b]IndexError[/b]: a list is indexed with an out-of-range number;\r\n[b]NameError[/b]: an unknown variable is used;\r\n[b]SyntaxError[/b]: the code can't be parsed properly; \r\n[b]TypeError[/b]: a function is called on a value of an inappropriate type;\r\n[b]ValueError[/b]: a function is called on a value of the correct type, but with an inappropriate value.\r\n[note]Python has several other built-in exceptions, such as ZeroDivisionError and OSError. Third-party libraries also often define their own exceptions.[/note]"}]}}